lambdas:
  player:
    code: player
    handler: index.handler
    runtime: nodejs4.3
    description: Teaches Alexa how to play CBC podcasts
    memory: 128
    policies:
      full_dynamodb_plus_logs:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - dynamodb:*
            Resource: "arn:aws:dynamodb:*:*:table/skill-cbc-podcasts"
            Effect: "Allow"
          -
            Action:
              - cloudwatch:DeleteAlarms
              - cloudwatch:DescribeAlarmHistory
              - cloudwatch:DescribeAlarms
              - cloudwatch:DescribeAlarmsForMetric
              - cloudwatch:GetMetricStatistics
              - cloudwatch:ListMetrics
              - cloudwatch:PutMetricAlarm
              - datapipeline:ActivatePipeline
              - datapipeline:CreatePipeline
              - datapipeline:DeletePipeline
              - datapipeline:DescribeObjects
              - datapipeline:DescribePipelines
              - datapipeline:GetPipelineDefinition
              - datapipeline:ListPipelines
              - datapipeline:PutPipelineDefinition
              - datapipeline:QueryObjects
              - iam:ListRoles
              - sns:CreateTopic
              - sns:DeleteTopic
              - sns:ListSubscriptions
              - sns:ListSubscriptionsByTopic
              - sns:ListTopics
              - sns:Subscribe
              - sns:Unsubscribe
              - sns:SetTopicAttributes
              - lambda:CreateFunction
              - lambda:ListFunctions
              - lambda:ListEventSourceMappings
              - lambda:CreateEventSourceMapping
              - lambda:DeleteEventSourceMapping
              - lambda:GetFunctionConfiguration
              - lambda:DeleteFunction
            Resource: "*"
            Effect: "Allow"
          -
            Action:
              - "logs:*"
            Resource: "*"
            Effect: "Allow"
